#!/bin/bash
. /etc/init.d/functions

start() {
    /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow - &
    touch /var/lock/subsys/hciattach
    success $"hciattach /dev/ttyAMA0 bcm43xx 921600 noflow - &: start"
    echo
}

stop() {
    killproc hciattach
    rm -f /var/lock/subsys/hciattach
    echo
}

case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  restart|reload|condrestart)
      stop
      start
      ;;
  *)
      echo $"Usage: $0 {start|stop|restart|reload|status}"
  exit 1
esac

exit 0
